#!/usr/bin/python3

ADAPTER_NAME = "hci0"

BLUEZ_SERVICE_NAME = "org.bluez"
BLUEZ_NAMESPACE = "/org/bluez/"
DBUS_PROPERTIES="org.freedesktop.DBus.Properties"
DBUS_OM_IFACE = 'org.freedesktop.DBus.ObjectManager'

ADAPTER_INTERFACE = BLUEZ_SERVICE_NAME + ".Adapter1"
DEVICE_INTERFACE = BLUEZ_SERVICE_NAME + ".Device1"

RESULT_OK = 0
RESULT_ERR = 1
RESULT_ERR_NOT_SUPPORTED = 2
RESULT_ERR_WRONG_STATE = 3
RESULT_ERR_ACCESS_DENIED = 4
RESULT_ERR_BAD_ARGS = 5
RESULT_ATTACH_FAILED = 6
RESULT_SEND_FAILED = 7

ACTION_GENERIC_ON_OFF_SET_UNACK = "generic_onoff_set_unack"
ACTION_LIGHT_HSL_SET_UNACK = "light_hsl_set_unack"
